name: CI/CD

on:
  push:
    branches: [main, feature/*]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yaml
          activate-environment: snakemake-starter
          auto-activate-base: false

      - name: Add dev dependencies
        run: conda env update --name snakemake-starter -f environment-dev.yaml

      - name: Run Snakemake lint
        run: snakemake -s workflow/Snakefile --lint

      - name: Set up data
        run: make setup-linux

      - name: Clean previous Snakemake state
        run: rm -rf .snakemake results logs || true

      # We can do this for now as the pipeline is lightweight
      - name: Run pipeline to produce reference outputs
        run: snakemake -s workflow/Snakefile --cores 1 --forceall

      - name: Generate unit tests
        run: snakemake -s workflow/Snakefile --generate-unit-tests tests/.generated

      - name: Run unit tests
        run: pytest -q tests/.generated || true

      - name: Cleanup generated tests
        if: always()
        run: rm -rf tests/.generated
