name: CI/CD

on:
  push:
    branches: [main, feature/*]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Sync dependencies (uv)
        run: uv sync

      - name: Run Snakemake lint
        run: uv run snakemake --lint

      # We can do this for now as the pipeline is lightweight
      - name: Run pipeline to produce reference outputs
        run: uv run snakemake --cores 1

      - name: Generate unit tests
        run: uv run snakemake --generate-unit-tests tests/.generated

      - name: Run unit tests
        run: uv run pytest -q tests/.generated

      - name: Cleanup generated tests
        if: always()
        run: rm -rf tests/.generated